#!/usr/bin/env node
/*
 * Lightweight CLI for the Turbo1k stream ledger.
 *
 * Usage examples:
 *   node update-ledger.js add --stream service-arbitrage --date 2026-05-05 --income 0 --hours 0 --notes "initial"
 *   node update-ledger.js list
 *   node update-ledger.js list --stream micro-saas
 *   node update-ledger.js kill --stream polymarket-research --reason "below trajectory"
 *   node update-ledger.js revive --stream polymarket-research
 *   node update-ledger.js summary
 *
 * Writes both ledger.json (canonical) and ledger.js (window.LEDGER_DATA shim
 * for dashboard.html to load via <script> in file:// contexts).
 */

const fs = require('fs');
const path = require('path');
const { parseArgs } = require('util');

const HERE = __dirname;
const JSON_PATH = path.join(HERE, 'ledger.json');
const JS_PATH = path.join(HERE, 'ledger.js');

function readLedger() {
  if (!fs.existsSync(JSON_PATH)) {
    fail(`ledger.json not found at ${JSON_PATH}`);
  }
  try {
    return JSON.parse(fs.readFileSync(JSON_PATH, 'utf8'));
  } catch (e) {
    fail(`Failed to parse ledger.json: ${e.message}`);
  }
}

function writeLedger(data) {
  const json = JSON.stringify(data, null, 2) + '\n';
  fs.writeFileSync(JSON_PATH, json);
  const js =
    '// Auto-generated by update-ledger.js — do not edit by hand.\n' +
    '// Mirrors ledger.json so dashboard.html works in file:// without fetch.\n' +
    'window.LEDGER_DATA = ' + JSON.stringify(data, null, 2) + ';\n';
  fs.writeFileSync(JS_PATH, js);
}

function fail(msg) {
  console.error(`error: ${msg}`);
  process.exit(1);
}

function findStream(data, id) {
  const s = data.streams.find((x) => x.id === id);
  if (!s) fail(`stream "${id}" not found. Streams: ${data.streams.map((x) => x.id).join(', ')}`);
  return s;
}

function parseDate(s) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(s)) fail(`date must be YYYY-MM-DD, got "${s}"`);
  return s;
}

function parseNumber(s, name) {
  const n = Number(s);
  if (!Number.isFinite(n)) fail(`${name} must be a number, got "${s}"`);
  return n;
}

function cmdAdd(rest) {
  const { values } = parseArgs({
    args: rest,
    options: {
      stream: { type: 'string' },
      date: { type: 'string' },
      income: { type: 'string' },
      hours: { type: 'string' },
      notes: { type: 'string', default: '' },
    },
    allowPositionals: false,
  });
  if (!values.stream) fail('--stream is required');
  if (!values.date) fail('--date is required (YYYY-MM-DD)');
  if (values.income === undefined) fail('--income is required');
  if (values.hours === undefined) fail('--hours is required');

  const data = readLedger();
  const stream = findStream(data, values.stream);
  const entry = {
    date: parseDate(values.date),
    income_usd: parseNumber(values.income, 'income'),
    time_hours: parseNumber(values.hours, 'hours'),
    notes: values.notes || '',
  };
  stream.entries.push(entry);
  stream.entries.sort((a, b) => a.date.localeCompare(b.date));
  writeLedger(data);
  console.log(`✓ added entry to "${stream.id}":`, entry);
}

function cmdList(rest) {
  const { values } = parseArgs({
    args: rest,
    options: { stream: { type: 'string' } },
    allowPositionals: false,
  });
  const data = readLedger();
  const streams = values.stream ? [findStream(data, values.stream)] : data.streams;
  for (const s of streams) {
    console.log(`\n[${s.id}] ${s.name} (${s.status})`);
    if (!s.entries.length) {
      console.log('  (no entries)');
      continue;
    }
    for (const e of s.entries) {
      const note = e.notes ? `  — ${e.notes}` : '';
      console.log(`  ${e.date}  $${e.income_usd.toFixed(2).padStart(8)}  ${e.time_hours.toFixed(2).padStart(6)}h${note}`);
    }
  }
}

function cmdKill(rest) {
  const { values } = parseArgs({
    args: rest,
    options: {
      stream: { type: 'string' },
      reason: { type: 'string', default: '' },
    },
  });
  if (!values.stream) fail('--stream is required');
  const data = readLedger();
  const stream = findStream(data, values.stream);
  stream.status = 'killed';
  stream.killed_at = new Date().toISOString().slice(0, 10);
  if (values.reason) stream.kill_reason = values.reason;
  writeLedger(data);
  console.log(`✓ killed "${stream.id}"${values.reason ? ` (${values.reason})` : ''}`);
}

function cmdRevive(rest) {
  const { values } = parseArgs({
    args: rest,
    options: { stream: { type: 'string' } },
  });
  if (!values.stream) fail('--stream is required');
  const data = readLedger();
  const stream = findStream(data, values.stream);
  stream.status = 'active';
  delete stream.killed_at;
  delete stream.kill_reason;
  writeLedger(data);
  console.log(`✓ revived "${stream.id}"`);
}

function cmdSummary() {
  const data = readLedger();
  const today = new Date().toISOString().slice(0, 10);
  console.log(`Turbo1k ledger — ${today}`);
  console.log('═'.repeat(70));
  for (const s of data.streams) {
    const totalIncome = s.entries.reduce((a, e) => a + e.income_usd, 0);
    const totalHours = s.entries.reduce((a, e) => a + e.time_hours, 0);
    const rate = totalHours > 0 ? totalIncome / totalHours : 0;
    console.log(
      `[${s.status.padEnd(7)}] ${s.id.padEnd(22)} $${totalIncome.toFixed(2).padStart(8)} | ${totalHours.toFixed(1).padStart(6)}h | $${rate.toFixed(2)}/hr`,
    );
  }
}

function cmdHelp() {
  console.log(`Turbo1k ledger CLI

Commands:
  add      Append a new entry to a stream
           --stream ID --date YYYY-MM-DD --income N --hours N [--notes "..."]

  list     Print entries (all streams, or filter by --stream ID)

  kill     Mark a stream killed (--stream ID [--reason "..."])
  revive   Mark a killed stream active again (--stream ID)

  summary  Per-stream lifetime totals + $/hour
  help     Print this message

The CLI rewrites both ledger.json and ledger.js (the latter is a
window.LEDGER_DATA shim for dashboard.html in file:// contexts).
`);
}

const [, , cmd, ...rest] = process.argv;
switch (cmd) {
  case 'add':
    cmdAdd(rest);
    break;
  case 'list':
    cmdList(rest);
    break;
  case 'kill':
    cmdKill(rest);
    break;
  case 'revive':
    cmdRevive(rest);
    break;
  case 'summary':
    cmdSummary();
    break;
  case 'help':
  case '--help':
  case '-h':
  case undefined:
    cmdHelp();
    break;
  default:
    fail(`unknown command "${cmd}". Run "node update-ledger.js help"`);
}
